- hosts: swarm
  become: true
  become_method: sudo
  tasks:
    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'gnupg2', 'python-pip', 'virtualenv', 'python3-setuptools']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/debian stretch stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest
      loop: ['docker-ce', 'docker-ce-cli', 'containerd.io']

    - name: Install Docker Module for Python
      pip:
        name: docker, jsondiff, pyyaml

    - debug:
        msg: "{{ hostvars['master-node']['ansible_host'] }}"

    - name: Init new swarm
      docker_swarm:
        state: present
        advertise_addr: "{{ hostvars['master-node']['ansible_host'] }}"
      when: master is defined and master|bool
      register: swarm_info

    - set_fact:
        manager_token: "{{ swarm_info.swarm_facts.JoinTokens.Manager }}"
        worker_token: "{{ swarm_info.swarm_facts.JoinTokens.Worker }}"
      when: master is defined and master | bool

    - name: Join to swarm manager
      docker_swarm:
        state: join
        advertise_addr: "{{ ansible_host }}"
        join_token: "{{ hostvars['master-node']['manager_token'] }}"
        remote_addrs: "{{ hostvars['master-node']['ansible_host'] }}:2377"
      when: master is not defined and not master | bool

    - name: Join to swarm worker
      docker_swarm:
        state: join
        advertise_addr: "{{ ansible_host }}"
        join_token: "{{ hostvars['master-node']['worker_token'] }}"
        remote_addrs: "{{ hostvars['master-node']['ansible_host'] }}:2377"
      when: master is not defined and not master | bool

    - name: encrease vm.map_max_count
      command: sysctl -w vm.max_map_count=262144
