- hosts: nginx
  tasks:
    - name: Create a jenkins container
      docker_container:
        name: jenkins
        image: jenkins/jenkins
        ports:
          - "8080:8080"
        volumes:
          - ./jenkins:/var/jenkins_home
      become: true
      become_method: sudo
